title: AAAAA Lab
description: Advanced · Analytical · Adaptive · Adventurous · Aspiring
url: ""
baseurl: ""
lang: en
markdown: kramdown
kramdown:
  input: GFM

collections:
  research:
    output: true
    permalink: /research/:name/
  projects:
    output: true
    permalink: /projects/:name/
  people:
    output: true
    permalink: /people/:name/

defaults:
  - scope:
      path: ""
      type: research
    values:
      layout: research-area
  - scope:
      path: ""
      type: projects
    values:
      layout: ongoing-project
      nav: projects
  - scope:
      path: ""
      type: people
    values:
      layout: member
      nav: people

exclude:
  - brand-spec.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - vendor
  - people/member-template

